cores: 1
forward: false
fwi: true
job_extra: [-e slurm-%j.err, -o slurm-%j.out, '--time=72:00:00', --requeue, --job-name="dask-job"]
memory: 2
model_size: 17000.0
mute_depth: 12
n_workers: 4
nrecs: 426
nshots: 16
processes: 1
project: project-name
queue: queue-name
rec_depth: 80.0
shot_batch_size: 4
solver_params: {dt: 4.0, dtype: float32, f0: 0.004, model_name: marmousi2, nbl: 50,
  parfile_path: ./marmousi2/parameters_hdf5/, shotfile_path: ./marmousi2/shots/, space_order: 8,
  t0: 0.0, tn: 5000.0}
src_depth: 40.0
use_local_cluster: true
vmax: 4.688
vmin: 1.377
